Workflow:
  name: preprocess_gih
  harpy-version: 4.1.1
  linkedreads:
    type: none
  reports:
    skip: false
  snakemake:
    absolute: snakemake --snakefile /local/workdir/pd348/time-series-shad/Preproc_S2/workflow/workflow.smk --configfile /local/workdir/pd348/time-series-shad/Preproc_S2/workflow/workflow.yaml --profile /local/workdir/pd348/time-series-shad/Preproc_S2/workflow/profile.yaml
    relative: snakemake --snakefile Preproc_S2/workflow/workflow.smk --configfile Preproc_S2/workflow/workflow.yaml --profile Preproc_S2/workflow/profile.yaml
    conda-envs:
    - qc
    - preprocess
Parameters:
  ME-sequence: AGATGTGTATAAGAGACAG
  ME-mismatch: 2
Inputs:
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_028.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_004.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_005.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_031.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_031.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_005.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_006.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_017.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_018.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_029.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_030.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_013.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_014.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_014.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_030.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_031.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_021.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_022.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_026.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_027.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_007.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_008.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_019.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_020.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_020.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_021.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_031.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_032.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_029.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_018.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_019.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_021.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_022.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_008.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_009.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_020.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_021.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_001.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_001.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_015.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_016.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_010.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_006.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_007.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_009.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_010.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_029.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_030.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_024.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_025.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_006.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_008.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_018.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_024.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_025.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_026.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_012.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_010.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_011.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_022.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_023.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_002.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_003.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_028.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_029.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_019.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_020.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_023.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_024.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_027.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_028.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_021.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_022.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_005.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_006.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_009.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_014.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_015.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_015.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_002.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_012.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_013.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_001.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_002.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_011.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_012.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_023.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_005.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_006.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_011.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_012.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_025.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_010.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_017.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_001.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_014.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_015.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_027.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_002.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_026.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_026.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_032.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_004.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_024.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_015.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_016.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_027.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_028.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_024.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_027.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_030.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_007.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_008.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_013.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_016.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_027.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_004.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_005.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_015.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_016.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_017.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_003.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_008.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_025.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_029.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_004.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_006.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_007.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_018.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_019.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_020.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_022.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_023.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_003.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_009.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_028.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_017.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_018.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_023.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_030.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_021.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_022.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_018.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_019.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_030.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_032.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_033.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_011.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_012.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_012.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_013.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_014.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_024.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_025.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_025.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_026.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_026.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_028.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_001.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_017.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_002.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_003.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_003.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_019.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_011.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_032.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_033.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_001.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_013.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_016.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_017.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_029.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Miramichi_031.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_002.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_020.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_003.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_005.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_008.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_009.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_009.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_010.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_010.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_011.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_014.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_023.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Kennetcook_031.R1.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_013.R2.fq.gz
- /local/workdir/shad/shad-time-series/FASTQ/shad-2/S2_Lahave_016.R1.fq.gz
